### ISSUE TITLE
Multiple container tabs opened on clicking a link

### ISSUE THREAD

**Issue by krishnanunnir** [mozilla/multi-account-containers#1617]
- Multi-Account Containers Version:
- Operating System + Version: Mac OS Catalina 10.15.1
- Firefox Version: 72.01
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When I am trying to open a youtube video from Duckduckgo videos, the same video gets opened in multiple tabs

### Expected behavior
Only one tab should open containing the video

### Steps to reproduce
1. Search for a keyword on DuckDuckGo videos
2. Choose a youtube option from the videos

**Comment by grouvig** [comment]
Same issue, when opening a link from one container tab to another container tab with middle click, two or more tabs are opened for the target container.

I reproduce it with a facebook container and a google container:
With only one tab open in Firefox I google facebook in this tab.
Then I middle click facebook.
This opens two tabs in facebook container.

In can reproduce it everytime I am in any container and then open a link with middle click to another container.

Doing the same with duckduckgo, instead of google, for which I have no container, only opens one facebook tab as expected.


Now with only one tab open in firefox, I open facebook in this tab.
In another tab I google facebook.
Then I middle click facebook.
Now only one facebook tab is opened as expected.

Conclusion:
Everytime I am in a container a middle click on a link opens two container tabs if there is not another tab already opened for the target container.

**Comment by krishnanunnir** [comment]
@grouvig Woah! that is pretty comprehensive. Great work man.

I had ditched firefox for a while and came back, I didn't face this issue afterwards,  don't know why.

**Comment by sammcj** [comment]
Same issue here on Firefox 85.0b9 (64bit) macOS Big Sir 11.1.

**Comment by siffegh** [comment]
This problem has supposedly been resolved in a couple of other bugs, but it persists for me.

Win7/FF 87.0/FF Multi-Account Containers 7.3.0

From within a containerized site, clicking a link to a different containerized site opens two tabs.

**Comment by PladimirVutin** [comment]
This is also still happening for me.

Windows 10 / Firefox Developer 88.0b9 (64-bit) / Firefox Multi-Account Containers 7.3.0

When I click a link from a Reddit container that opens in Twitter, Amazon or Facebook containers I got double of the new container tab.

**Comment by sammcj** [comment]
Can confirm is still an issue in Firefox 88.0b9 on macOS, Multi-Account Containers Version 7.3.0

**Comment by siffegh** [comment]
Still happening on FF 88.0.

**Comment by grahamperrin** [comment]
https://github.com/mozilla/multi-account-containers/issues/1617#issuecomment-807496689

> … From within a containerized site, clicking a link to a different containerized site opens two tabs.

With `blog.mozilla.org` assigned to _Personal_ and `www.mozilla.org` assigned to _Work_: 

* at the foot of https://blog.mozilla.org/ a <kbd>Control</kbd>-Click on **Firefox** opens just one new tab in the _Work_ container. 

@krishnanunnir please, can you give this issue a title that is distinctive and (partly) self-explanatory? Thanks

**Comment by grahamperrin** [comment]
https://github.com/mozilla/multi-account-containers/issues/1617#issuecomment-713043786

> middle click

For those of us without middle-clicks: 

[Use mouse shortcuts to perform common tasks in Firefox | Firefox Help](http://mzl.la/1xKrRYF)

>> Open link in new Tab | Middle-click on Link

**Comment by grouvig** [comment]
[Comment form grahamperrin](https://github.com/mozilla/multi-account-containers/issues/1617#issuecomment-829432964)
>     * at the foot of https://blog.mozilla.org/ a Control-Click on **Firefox** opens just one new tab in the _Work_ container.

In my case with a Control-Click on a link to a different containerized site, it opens two tabs in the target container.

**Comment by grahamperrin** [comment]
> In my case with a Control-Click …

With reference to your case: 

* steps at https://gist.github.com/grahamperrin/944503076e3d86ac464fdd5b2b96e85c 

Following the steps, a screen recording: 

https://user-images.githubusercontent.com/192271/116642531-0a08b300-a967-11eb-8058-7a6312bae269.mp4

In the final thirty seconds, <kbd>Control</kbd>-Click within a Google _container_ produces: 

* a single new tab in a _Facebook_ container
* **no duplication**. 

Please, can someone expand the steps? Or provide alternative steps; be precise. 

To make this issue **reproducible with a new profile**. 

Thanks

**Comment by grouvig** [comment]
I found what happens in my case.
The problem is related to this add-on https://addons.mozilla.org/en-US/firefox/addon/container-outgoing-links/.
After disabling this add-on it works as expected.

But I loose the ability, when clicking a link in a containerized tab to open non containerized websites in the default container.
This is a feature I really miss in multi-account-containers.

**Comment by grahamperrin** [comment]
Re: opening post <https://github.com/mozilla/multi-account-containers/issues/1617#issue-552199480>: 

@krishnanunnir is there truly no other add-on? 

Is Multi-Account Containers the one and only extension to Firefox?

**Comment by mannfuri** [comment]
> > In my case with a Control-Click …
> 
> With reference to your case:
> 
>     * steps at https://gist.github.com/grahamperrin/944503076e3d86ac464fdd5b2b96e85c
> 
> 
> Following the steps, a screen recording:
> 2021-04-30.03.37.02.mp4
> 
> In the final thirty seconds, Control-Click within a _Google_ container produces:
> 
>     * a single new tab in a _Facebook_ container
> 
>     * **no duplication**.
> 
> 
> Please, can someone expand the steps? Or provide alternative steps; be precise.
> 
> To make this issue **reproducible with a new profile**.
> 
> Thanks

it will happend if you put facebook into you bookmark , and click the bookmark.

**Comment by mannfuri** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/new-tab-from-location-bar/

for me , this extension make this happen.
