### ISSUE TITLE
"Open this site in your assigned container?" not working

### ISSUE THREAD

**Issue by laborissa** [mozilla/multi-account-containers#1703]
On OS X, since new Firefox update (75.0) I am not able to open the same page in two different containers, for example 2 gmail accounts.

**Comment by sjagoe** [comment]
The issue appears on Linux and Windows as well as OSX noted above.

I use temporary containers as well, occasionally opening "pinned" sites in a temporary container to have a clean state with regards to cookies, etc. This is no longer possible; even choosing to open in current container, the container is switched to the assigned permanent container.

**Comment by Doc73** [comment]
Yes, I can confirm that this issue is also in my Debian 10 Buster.

I think it is related to synchronization problems: the synchronization becomes very slow and wants to set gmail on a container, even if you delete it from it. Not even new bookmarks can be synced!

Disabling this plugin "solves" all issues! :cry:

**Comment by tcoopman** [comment]
Same thing on Archlinux.
Disabling sync does not seem to change anything

**Comment by nabeelr** [comment]
Same here too!

It always opens it in the assigned container, despite choosing to leave it in it's existing container.

**Comment by nabeelr** [comment]
Just tested it on a computer that was still on 74.0.1, it works fine, upon updating to 75.0 it immediately broke it.

**Comment by yoasif** [comment]
What are the steps to reproduce the bug?

**Comment by nabeelr** [comment]
Create a container, let's call it CBC.

Open a new tab in the CBC container.

Go to cbc,ca

Check the "always open in this container" checkbox.

Open another tab in a different container

Go to cbc.ca

When prompted if you want to open it in the CBC container, opt to leave it in it's existing container.

Watch as it miraculously opens in the CBC container anyways.

Curse, punch your keyboard, cry, weep, give up on life, and become a hermit.

**Comment by yoasif** [comment]
```
 8:45.23 INFO: No more integration revisions, bisection finished.
 8:45.23 INFO: Last good revision: 10059adf004590aca187aab75d0e46a6cfde1e44
 8:45.23 INFO: First bad revision: 99066bbd1b3a288471f2bf7f59f1c99da42610a1
 8:45.23 INFO: Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=10059adf004590aca187aab75d0e46a6cfde1e44&tochange=99066bbd1b3a288471f2bf7f59f1c99da42610a1
```

Should this be reported to Firefox's bugzilla?

**Comment by nabeelr** [comment]
Maybe? Not sure, because there was an update to multi containers today, and this is when I noticed the problem. It seems other people are in the same boat.

So it may be FF or it may be Multi-Containers... Or maybe even both.

Cross posing it is probably a good idea.

**Comment by fmiyata** [comment]
a workaround is to open the container you want to use..
then, somehow, click on a link that goes to the url you want to access..

for instance, if you want to open a Gmail account:
- open the container you need (blank page)
- open https://www.bing.com/
- search for Gmail
- click on Gmail link

**Comment by tcoopman** [comment]
@fmiyata that doesn't seem to work for me. When I click that link, a new tab opens for gmail with the same problem

**Comment by fmiyata** [comment]
> 
> 
> @fmiyata that doesn't seem to work for me. When I click that link, a new tab opens for gmail with the same problem

it shouldn't be opening in a new tab..
aren't you clicking with the mouse wheel?

it's working here on 2 pcs (both Windows 10), for all my containers..

**Comment by nabeelr** [comment]
I've had some limited success with the switch container extension, but usually, I want to catch a web-page before it gets a chance to hit my container with all the cookies and whatnot, for tracking and privacy purposes.

**Comment by tcoopman** [comment]
> > @fmiyata that doesn't seem to work for me. When I click that link, a new tab opens for gmail with the same problem
> 
> it shouldn't be opening in a new tab..
> aren't you clicking with the mouse wheel?
> 
> it's working here on 2 pcs (both Windows 10), for all my containers..

If I click on a link that is not assigned to a specific container it opens in the same tab. When I click on a link that is assigned, a new tab is opened and it doesn't work.

Is there a way to remove the "always open in this container" for urls? because that would be a possible workaround.

**Comment by garywill** [comment]
This bug makes me think of a similar bug https://github.com/mozilla/multi-account-containers/issues/1312 ( and a PR which seems to solve it https://github.com/mozilla/multi-account-containers/pull/1599) 

Two bugs both stop opening 1 url in different containers. That bug was not as terrible as this bug.

**Comment by corytrevor1** [comment]
Same problem here.

**Comment by groovecoder** [comment]
@DeadlySurprise made a quick fix for this particularly nasty workflow-busting bug. I've merged it and will release the fix on Monday.

**Comment by nabeelr** [comment]
Just did some testing, on FF 73.0.1, the problem still occurs with the current version of multi-account containers, 6.2.3.

So maybe it's a bug with the extension.

**Comment by groovecoder** [comment]
Submitted 6.2.5 to AMO. Should be reviewed & distributed soon.

**Comment by Vinnl** [comment]
Just got the updated 6.2.5, and I confirm that it now works again. Thanks for the quick resolution!

**Comment by fmiyata** [comment]
still not working here.. actually it's worse now..

1 - It doesn't prompt anymore:
     "Open this site in your assigned container?"
     it just opens it in the the wrong container

2 - the workaround I mentioned before, also doesn't work anymore
     when I open bing.com and click on the gmail link, it just opens it in a new tab using the wrong container again

(Windows 10, FF 75.0, Multi container v 6.2.5)

**Comment by sjagoe** [comment]
@fmiyata That sounds like the behaviour if the "Remember my decision for this site" option was selected when the prompt was accepted; version 6.2.5 has fixed the issue for me.

Try going to the site that isn't prompting and uncheck and re-check the `Always open in <container>` option in the multi-account-containers dropdown to reset the decision in case it was enabled by accident.

**Comment by fmiyata** [comment]
@sjagoe You were right, it worked.. Thanks!

I didn't notice this checkbox before..

I was trying to access gmail.com (which redirects to google.com subdomains)
so I had to uncheck the "Always open in <container>" at www.google.com

**Comment by samoylenkodmitry** [comment]
It absolutely doesn't remember when I check "Remember my decision for this site" checkbox.

**Comment by achernyakevich-sc** [comment]
@samoylenkodmitry No problem. Just check configuration of the container that your site is opening in. If this container's list of sites will have this site then you could remove it and it will fix the problem. :)
