### ISSUE TITLE
Menu open behind something or not at all

### ISSUE THREAD

**Issue by ervee** [mozilla/multi-account-containers#1776]
- Multi-Account Containers Version: 6.2.5
- Operating System + Version: Windows 10 amd64 build 1803 (yes...)
- Firefox Version: 78.0.1 (64-bit)
- Other installed Add-ons + Version + Enabled/Disabled-Status: I tried with all but Multi-Account Containers active
Name 	Version 	Enabled 	ID
Amazon.com	1.1	true	amazondotcom@search.mozilla.org
Auto Tab Discard	0.3.6	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Bing	1.1	true	bing@search.mozilla.org
Cisco Webex Extension	1.8.0	true	ciscowebexstart1@cisco.com
DuckDuckGo	1.0	true	ddg@search.mozilla.org
eBay	1.0	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	6.2.5	true	@testpilot-containers
Ghostery – Privacy Ad Blocker	8.5.1	true	firefox@ghostery.com
Google	1.0	true	google@search.mozilla.org
HTTP/2 Indicator	3.0	true	spdyindicator@chengsun.github.com
HTTPS Everywhere	2020.5.20	true	https-everywhere@eff.org
Wikipedia (en)	1.0	true	wikipedia@search.mozilla.org
Adblock Plus - free ad blocker	3.9	false	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
McAfee Endpoint Security Web Control	10.7.0.2	false	{cb40da56-497a-4add-955d-3377cae4c33b}

### Actual behaviour:

I just installed the Multi-Account Containers Add-on and the menu to show the containers does not open. Or well it looks like it opens behind the rest of Firefox... I restarted Firefox, disabled all other Add-ons, moved the icon around to other places and bars, tried some different (color)themes but nothing I do will eventually show the menu. Here you can barely see the top part (about a pixel or two) of the pop-up menu and the triangle pointing to the Add-on icon.

![image](https://user-images.githubusercontent.com/4435930/86335251-8bf85480-bc4e-11ea-9ac7-87ffa19eed77.png)

### Expected behaviour

Show the menu / containers

### Steps to reproduce
1. Install Multi-Account Containers Add-on
2. Click the Multi-Account Containers icon
3. See nothing :)

### Notes

PS: In the issue template you have a typo "behavior" instead of "behaviour" twice?

**Comment by maxgrenderjones** [comment]
It went away when I disabled and re-enabled the add-on (but had then lost all my settings). However it's come back again...

Aside from the strange UI, it also stops opening website in preselected containers

**Comment by groovecoder** [comment]
Can you reproduce this in a profile with no other add-ons installed?

**Comment by ervee** [comment]
I just created a brand new profile, installed the Add-on and it shows the first start walk-through like it should. I'll start disabling Add-ons in my main profile to see if one brakes m.a.c.

**Comment by ervee** [comment]
I just disabled every add-on in about:addons except multi account containers and it still does not show the window/balloon/thing when I click the icon. I don't get it.

**Comment by maxgrenderjones** [comment]
If you move it to the overflow menu you can get it to display. But there's nothing there!
<img width="400" alt="Screenshot 2020-07-08 at 23 32 42" src="https://user-images.githubusercontent.com/6059365/86977046-b036c280-c173-11ea-89d7-195295c2735b.png">

<img width="397" alt="Screenshot 2020-07-08 at 23 32 48" src="https://user-images.githubusercontent.com/6059365/86977042-ae6cff00-c173-11ea-9f23-0c52637f86a4.png">

**Comment by tjahyaf** [comment]
This is what shows up in Debug Add-Ons
![console-log](https://user-images.githubusercontent.com/22611678/87222613-af867200-c3a7-11ea-9add-486a889c8769.png)

**Comment by andrewkslv** [comment]
With the new update I wasn't be able to open container with cmd+period. It bugs out. It's also not possible to navigate with up / down arrows.

**Comment by ervee** [comment]
When I open the addon debugger and then open the addon itseld this all is logged:

```
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Unchecked lastError value: Error: An unexpected error occurred background.js:14
Error: Can't find profile directory. 2 XULStore.jsm:66:15
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:831
Unchecked lastError value: Error: An unexpected error occurred 3 background.js:14
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 3 ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Unchecked lastError value: Error: An unexpected error occurred index.js:29
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 4 ExtensionStorageIDB.jsm:831
An unexpected error occurred 3 undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
sendRemoveListener on closed conduit {c2c003ee-bd69-42a2-b0e9-6f34222cb046}.962072674328 ConduitsChild.jsm:108
sendRemoveListener on closed conduit {c2c003ee-bd69-42a2-b0e9-6f34222cb046}.962072674308 3 ConduitsChild.jsm:108
sendRemoveListener on closed conduit {c2c003ee-bd69-42a2-b0e9-6f34222cb046}.962072674308 ConduitsChild.jsm:108
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 6 ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 7 ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 3 ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 3 ExtensionStorageIDB.jsm:831
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 6 ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: An unexpected error occurred undefined
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 4 ExtensionStorageIDB.jsm:831
Uncaught (in promise) Error: Failed to retrieve the identities or variation. We cannot continue. 
    init moz-extension://93df8974-2469-478e-9021-6456187dd77b/js/popup.js:67
    async* moz-extension://93df8974-2469-478e-9021-6456187dd77b/js/popup.js:1440
An unexpected error occurred:67:13
```

**Comment by tjahyaf** [comment]
It appears that this problem may be caused by corrupted Firefox profiles. I fixed mine by refreshing my Firefox profile and reinstalling the add-on. If you see any mention of `database` in the error log, try to refresh your profile and see if that could solve your problem.

**Comment by dannycolin** [comment]
Can you still reproduce in the latest Firefox? Btw, it looks like an issue on the browser side.

**Comment by ervee** [comment]
I think I eventually ended up starting from a fresh Firefox profile. And it works fine ever since.
