### ISSUE TITLE
breaks mail.google.com

### ISSUE THREAD

**Issue by D33M0N** [mozilla/multi-account-containers#1882]
- Multi-Account Containers Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
I get google error 400

### Expected behavior
I can read and send e-mail in mail.google.com

### Steps to reproduce
1. enable addon
2. contain mail.google.com into container
3. restart browser

### Notes
just disabling the addon and restarting the browser fixes it.

**Comment by kennethtran93** [comment]
You may need to sign in again as cookies are stored per container.  Also may need other google domains in that container as well to make it work.

**Comment by D33M0N** [comment]
other domains are needed in other containers aswell. I have more than one google account.

**Comment by kennethtran93** [comment]
It still works fine for me.  I have a container holding mail.google.com with two accounts, and just created another container and signed onto YouTube with a third account.  Everything still works fine.

**Comment by D33M0N** [comment]
which firefox? I have 81.0

**Comment by kennethtran93** [comment]
Same.  81.0.1 64-bit on Windows 10

**Comment by D33M0N** [comment]
Same. in Windows 10 in 81.0.1 it does work. In linux with Firefox 81.0 it does not.

**Comment by kennethtran93** [comment]
> 
> 
> Same. in Windows 10 in 81.0.1 it does work. In linux with Firefox 81.0 it does not.

Then maybe Firefox 81.0 is the culprit and it got fixed in 81.0.1?  It will usually be up to the platform maintainer to update the packages.  Else you can manually install Firefox here: https://www.mozilla.org/en-CA/firefox/linux/

**Comment by FlorianWendelborn** [comment]
@D33M0N make sure you’re doing the entire login process in the mail container, I previously hhad accounts.google.com set to open in Google automatically which of course messes with the login process

**Comment by D33M0N** [comment]
Upgraded my linux Firefox to 81.0.2. Still doesn't work for gmail. I can container youtube and stuff just fine, but mail, nope.

**Comment by tompreston** [comment]
I also have an issue with loading gmail in a Personal container. In my non-contained tabs I access my work's Google services, which has gmail disabled. Then, if I open mail.google.com in a Personal container I see the following page:

![Screenshot from 2020-11-03 13-42-13](https://user-images.githubusercontent.com/669843/98244420-54384b00-1f67-11eb-850e-2179c3ef2394.png)

Clicking Show Detailed Technical Info, reveals:
> Numerical code: 9

I can work around this by attempting to log into mail.google.com on a non-container tab, which reports:
> We are sorry, but you do not have access to Gmail. Please contact your organisation administrator for access.

Then the mail.google.com in the Personal container refreshes and works.

If I clear cookies, it works once, then subsequent visits break in the same way.

I think it's something to do with the non-container tabs cookies *infecting* the Personal container. Which gets rectified when I try to visit gmail in the non-container context.

**Comment by swt2c** [comment]
I am running into the same Temporary Error with Numerical code: 9 as @tompreston.  I am running Firefox 82.0.2 on Fedora 33 where I run several different Gmail accounts in different containers.  My workaround that fixes the issue is to go and delete cached data for mail.google.com.  What's weird is that I have NOT run into the same problem on my Ubuntu 18.04 machine where I have a similar setup with multiple Gmail accounts in different containers.

**Comment by tompreston** [comment]
@swt2c I'm also on Fedora 33 (updated my comment). What version of Firefox are you running on Ubuntu? I wonder if we can repeat this in fresh Fedora 22 and Fedora 33 virtual machines.

**Comment by swt2c** [comment]
On Ubuntu I currently have Firefox 83.0.  What's weird is that I have not reproduced this problem on my Fedora 33 machine for several days now.

**Comment by oktayaa** [comment]
As far as I can see the last step in the login process opens a new tab which is not inside the container so it can't access the cookies it just set. I don't know why it's working for some people though.

**Comment by tompreston** [comment]
@oktayaa What do you mean by "last step in the login process opens a new tab"? My understanding is that logging into mail.google.com doesn't open a new tab. And if it did, it would be still be in the current tab's container context - for example middle clicking a link in a Personal container tab opens a new tab in a Personal container.

**Comment by D33M0N** [comment]
> for example middle clicking a link in a Personal container tab opens a new tab in a Personal container.

unless the link uses different domain which you have put to different container. or limited current container to only use aaa, bbb and ccc domains whereas the new link is not part of any of them.

**Comment by oktayaa** [comment]
> 
> 
> @oktayaa What do you mean by "last step in the login process opens a new tab"? My understanding is that logging into mail.google.com doesn't open a new tab. And if it did, it would be still be in the current tab's container context - for example middle clicking a link in a Personal container tab opens a new tab in a Personal container.

I think I was limiting the container to mail.google.com only which is what I want to do, but since the login process is hitting other domains including accounts.google.com the container was creating a new tab (not google). 

There's already an open bug about not being able to add a domain to the list of container limited domains without actually going to that url. It's a pain to add google domains because they go through a bunch of redirects to set all of their cookies.

For now it seems to work when adding accounts.google.com and myaccount.google.com into the same container site list.

**Comment by freedriven** [comment]
Same issue happening with me:
ubuntu 23.04, firefox 118.0

Here's the cycle; get 400 error, create new container and it works for a while, then something happens (eg one of the many reasons one might need to provide password again), and I get the error again, repeat.

**Comment by joheightzero** [comment]
> Same issue happening with me: ubuntu 23.04, firefox 118.0
> 
> Here's the cycle; get 400 error, create new container and it works for a while, then something happens (eg one of the many reasons one might need to provide password again), and I get the error again, repeat.

Same issue here. This has led me to stop using container tabs.

**Comment by lovek323** [comment]
I'm also stuck on this one
