### ISSUE TITLE
Firefox 103 deleted multi-account-containers and all container data

### ISSUE THREAD

**Issue by GregDavidson** [mozilla/multi-account-containers#2400]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

I upgraded to Firefox 103 using Mint's aptitude tool.
I noticed the Multi-Account-Containers icon was gone
Turns out the extension was gone
I added Multi-Account-Containers back
All of my containers were gone

### Actual behavior

My containers are all gone

### Expected behavior

None of this should have happened!

### Additional informations

Firefox 103 under Linux Mint
--> I have backups of my filesystem,
--> What files should I restore?

### Provide a copy of Troubleshooting Information page

```plain text
I would like too, but I'm told it's too long and I can't send the report!
```

**Comment by GregDavidson** [comment]
Things are not as bad as they seemed.  The upgrade to 102 had also broken my Firefox sync.  Once I got that going again my containers were restored.

**Comment by GregDavidson** [comment]
Sorry, to Firefox 103.

**Comment by dannycolin** [comment]
> Things are not as bad as they seemed. The upgrade to Firefox 103 had also broken my Firefox sync. Once I got that going again my containers were restored.

Does that mean your issue is resolved? Also, right after the update, did all your addons were gone or only Multi-Account Containers?

**Comment by DesignatedJM02** [comment]
I signed into Sync via Firefox and my containers disappeared once Sync happened. Had this issue before so I stopped using Sync. I guess the issue still isn't fixed. I opened a BugZilla bug, but then they told me to come to the containers github repo.

**Comment by foss-** [comment]
Lost all custom containers in stable after opening and updating nightly. Custom containers are still in nightly. Tried signing out of sync in stable and login again which brought back custom containers to stable. This is always a bit nerve wracking and sync seems to be part of the problem as the custom containers did not return on sync and only after logout + login to sync.

**Comment by dannycolin** [comment]
Closing since OP mentioned it was resolved on for them.
