### ISSUE TITLE
Container tabs not sending Device ID for conditional access compliance.

### ISSUE THREAD

**Issue by MrMellie** [mozilla/multi-account-containers#2670]
### Before submitting a bug report

- [X] I updated to the latest version of Multi-Account Container and tested if I can reproduce the issue
- [X] I searched for existing reports to see if it hasn't already been reported

### Step to reproduce

1. Open Azure Portal (https://portal.azure.com) in a container tab to a tenant that uses Conditional Access Polices that require a compliant device.
2. Enter creds
3. Get error message that device is not compliant.

### Actual behavior

After trying to sign in, Entra/Azures gives an error message indicating my device is not compliant.

### Expected behavior

It should log in just like a non-container tab.

### Additional informations

The container tabs are not sending the device ID as a signal to enable logins to pass CAP where trusted devices are a requirement. Regulat tabs within Firefox are sending the device ID okay. This is not to be confused as a SSO issue - Windows SSO is turned OFF and not required for normal or container tabs in this scenario.

**Comment by bakulf** [comment]
@MrMellie can you reproduce this issue using private browsing instead of a container?

**Comment by MrMellie** [comment]
Hi, I haven't tried Private Browsing, but from memory, any private session doesn't send device ID either.

**Comment by VoskosSas** [comment]
Hi, I start to face the same issue, I have tried on an anonymous tab and it is the same error as with the containers.

**Comment by bakulf** [comment]
Thanks. Can you tell me how I can reproduce the issue?

**Comment by MrMellie** [comment]
Hi Balkuf, the steps to reproduce are in the initial post under Steps To Reproduce :)

**Comment by MrMellie** [comment]
Has anyone had a chance to look at this?
thanks

**Comment by molldk** [comment]
What makes you think this is a FF problem? This works for me in a non-container tab, any container tabs are not sending the device information however...

**Comment by MrMellie** [comment]
> What makes you think this is a FF problem? This works for me in a non-container tab, any container tabs are not sending the device information however...

It was working before the last update and then afterwards, it didn't. What version are you on? I know our CAP has not changed, it would be my team making the changes.

**Comment by molldk** [comment]
Firefox 133.0 (aarch64)

**Comment by MrMellie** [comment]
> What makes you think this is a FF problem? This works for me in a non-container tab, any container tabs are not sending the device information however...
> 
> Using Firefox on MacOS Sequoia v15.1.1 with M3 processor. Firefox Multi-Account Containers v8.2.0. **PlatformSSO enabled**. SSO works fine in a non-container tab. Any tabs from the addon is failing auth due to missing device id.

Now try and turn Single Sign On in the browser Off. The device ID should still be sent, but it isn't. I am not logging in to Azure with the same account I sign in to my device with (my regular user account)- I'm using my cloud admin account credential that is not used to sign in to my device.

If I understand the add-in Multi-Account Container correctly, it just surfaces underlying FF functionality with a GUI to manage your containers. Since raising the ticket 8 weeks ago, I've found you can do the same thing in a less user friendly way using the About:Config page with no add-in installed.

**Comment by molldk** [comment]
I'm using multiple accounts as well, the reasoning behind using containers is to have different accounts per container in my scenario (admin account being one of them). I've tested both with network.http.microsoft-entra-sso.enabled true and false. Even tried the option for private browsing, but this errors too.

I'm thinking, since the id is sent correctly from a non-container tab, that things are working in FF (without fully knowing the backend implementation). However, as soon you attempt any auth with a container-tab, the device ID is not send.

**Comment by MrMellie** [comment]
Yes, that is pretty much my scenario too. I have 8 (eight!) tenants to administer and I am using containers to isolate the admin account for each tenant. My normal user account (email etc) is used in Edge to completely isolate admin and standard accounts. I have the SSO setting turned on in Edge so it uses the account registered in Windows.

The non-container tab is used for the admin account on my primary tenant in which the device is hybrid joined. I will often have multiple tabs open per tenant, If I open a new tab in a container, it remembers who I'm logged in as and just opens the portal page with no grief. It uses to do this for my non-container tab too until the 133 update.

Now, in order for my main admin account to log in successfully, I have to enable Windows SSO in Firefox - this means I have to register my _admin_ account in Windows and every time I open a new tab I get a pop-up asking which account I want to use and I have to make sure to to select the right one. It's "only 1 click" but it slows down opening new tabs and over the course of the day builds up to a lot of inconvenience and potential for selecting the wrong account.

It also has the knock on effect of breaking Edge with the same problem, a pop-up to select the correct account for each new tab, even my corporate VPN does not open without prompting for an account now (it should just connect on boot up).

>I'm thinking, since the id is sent correctly from a non-container tab, that things are working in FF (without fully knowing the backend implementation).

My thinking is that sending the device ID has been (incorrectly) baked into the Windows SSO setting. I think I recall seeing you can turn SSO on in each container tab, something you could test maybe? I just don't want Windows SSO turned on at all in FF but I _do_ need the device ID to be sent so I can authenticate (enter my password and MFA per tenant) and get through Conditional Access.

https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#enable-windows-sso-in-a-specific-container

**Comment by dannycolin** [comment]
@mkaply I remember you implemented something around Windows SSO and containers. Would you have any idea if this is related?

**Comment by molldk** [comment]
My issue is on Mac with Platform SSO, but I might need to create an issue to not hijack this one? :)

**Comment by molldk** [comment]
The weird thing for me is that this seemed to work before we enabled PlatformSSO. But I can't rule out that my account was simply excluded from the compliant device check before. Nevertheless, the device id is not sent with requests from anywhere but a non-container tab as far as I can tell. If someone could point me to the source file, I could attempt to take a look, as I'm not really sure where to look.

**Comment by bakulf** [comment]
https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsHttpChannel.cpp#445-466
By reading this code, Firefox requires special prefs to enable Windows SSO for containers: `"network.http.windows-sso.container-enabled." + containerID`.

I think the right steps to fix this issue are the following:
- extend the ContextualIdentity API to support Windows SSO per containers
- implement the support for Window SSO per container in this add-on.

Temporary solution: set the pref manually in about:config. Please confirm that the issue is fixed by setting those boolean prefs to true.

**Comment by MrMellie** [comment]
Negative @bakulf, the device ID should be sent independant of the SSO flag setting on both non-container tabs and container tabs for a regular browser session. I need the device ID sent with Windows SSO turned Off. I sign in manually with my Admin and Test accounts in the containers but am still subject to Conditional Access Policies in Azure/Entra.

I beleive other people have requested Window/Platform SSO for containers (see my previous link) which your solution would solve, but that is not the requirement of the Issue I have rasied.

**Comment by molldk** [comment]
Agree the device id is more part of Entra Conditional Access, and not SSO only. You can still require a compliant device without full SSO implementation.

I see no reason why device-id isn't sent in all tabs, container based or not. SSO is independent from conditional access in this aspect.

**Comment by mkaply** [comment]
>I see no reason why device-id isn't sent in all tabs, container based or not. SSO is independent from conditional access in this aspect.

I'll be honest, I don't fully understand this (and Microsoft didn't bring it up when we did the implementation).

What sites would we send it to? We wouldn't send it to every site on the internet, that would be a privacy issue.

**Comment by MrMellie** [comment]
In my instance, it needs to go across in the saml token when signing into Microsoft sites (dozens of different portals) using my corporate IDs (so not consumer sites like Hotmail) -.e.g https://portal.azure.com, https://intune.microsoft.com, https://admin.microsoft.com etc etc

**Comment by mkaply** [comment]
So if I'm understanding, you want to be able to login manually using an account other than what is built in to your machine, but then still send the device ID so that conditional access (device specific access) works?

**Comment by molldk** [comment]
I'm assuming it is part of the protocol where the device certificate is used in auth as well. But it is really hard to find any guidance from Microsoft on how this should actually be implemented in applications like a browser. Most documentation you can find is either how to setup Conditional Access for validating devices, OR regular authentication flows, that doesn't seem to mention device compliance at all (probably checked in backend by Entra based on deviceid, certificate and Intune status).

Since this work in regular non-container tabs, maybe code from FF can provide a hint on how to replicate same behavior with containers?

**Comment by molldk** [comment]
So checking request header from a non-container tab and a container tab, I see more headers for the non-container tab. Specifically:
- x-ms-RefreshTokenCredential1
- x-ms-DeviceCredential
- x-ms-RefreshTokenCredential
- TE: trailers
 
The first 3 looks like generic Bearer tokens, so not sure if its because my browser is already logged on or something in relation to device compliance/client certs

**Comment by molldk** [comment]
Auth endpoint in these cases are:
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize

Tested logging in to Azure Portal with same account

**Comment by MrMellie** [comment]
Have you had any luck with Msft @mkaply ? (or got a "it's by design" type reply)

**Comment by MrMellie** [comment]
I'm also curious what changed between v130 and v133, as non-container tabs, at least, worked in v130.

**Comment by mkaply** [comment]
Microsoft said, and I quote:

"We don't want to support this pattern."

Nothing related to Windows SSO changed between 130 and 133 (that I know of)

If it definitely used to work, you can use mozregression:

https://mozilla.github.io/mozregression/

and we can figure out what happened.

**Comment by MrMellie** [comment]
"We don't want to support this pattern."

What on earth does that mean? We don't understand why an admin would want to sign on without SSO so we CBA to look at it? Typical MS fob off.

I'll have a go with mozregression tomorrow and let you know the results.

**Comment by MrMellie** [comment]
I tried MS regression, it didn't seem to get stuck at v131 and not go back any further* so didn't get anything usefull from it.

*that or I'm using it wrong.

**Comment by mkaply** [comment]
So you might want to set the date way back since we don't know when it started.

**Comment by molldk** [comment]
I found this documentation that seems to describe the protocols used for this:
https://learn.microsoft.com/en-us/entra/identity/devices/concept-primary-refresh-token

I still have issues when using container tabs for this - it might be supported on Windows, but no luck so far in Mac OS :( Hopefully something similar to Windows will be added for Mac OSX.

**Comment by mkaply** [comment]
Can you check this in a recent version? We fixed a problem where we didn't send tokens if one of them was empty.

https://bugzilla.mozilla.org/show_bug.cgi?id=1945596

It was in 137.

Although it's possible it might be this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1934809

**Comment by molldk** [comment]
I am on 137.0.2 after recent patching.
So far I can connect to sites that I previously had trouble with, which is positive news! So it might in fact be that (at least for me on Mac platform). I need to check a bit further to verify, as I have custom policies in place that might affect it though.

**Comment by molldk** [comment]
Ah, still not working for me..
![Image](https://github.com/user-attachments/assets/e05eb96c-1416-4ecf-a85b-23214be9b14e)

Same URL in a non-container tab works fine. As soon as its opened in a container tabs, the device state is not working..

**Comment by mkaply** [comment]
OK, so by default we don't send SSO in containers, but you can add it by setting a preference:

https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#13275

**Comment by molldk** [comment]
Thank you @mkaply! I got this working for me now. I feel like I have tried this exact approach, but maybe it was a parameter specifically for windows based sso as that appear most common while searching for a solution.

Solution for me, Firefox 137.0.2 (aarch64), on Mac:
1. Find Firefox profile folder, visible from about:profiles
2. Identity container id (as explained [here](https://github.com/mozilla/multi-account-containers/wiki/Frequently-asked-questions#enable-windows-sso-in-a-specific-container)) by opening containers.json and note userContextId for the container that should be enabled. 
3. go to about:config and paste: "network.http.microsoft-entra-sso.container-enabled.CONTAINERID", replace with correct ID, add it and make sure boolean is set to true. Restarting the app is not necessary.

Note the difference based on platform:
**Windows:** network.http.windows-sso.container-enabled.CONTAINERID
**Mac:** network.http.microsoft-entra-sso.container-enabled.CONTAINERID

This appear resolved for me now.

**Comment by molldk** [comment]
I would suggest adding the Mac specific settings in the FAQ, but you cannot do PR for the wiki. Tagging @dannycolin that seems to make changes in Wiki. Let me know if you want a dedicated issue for this suggestion.

Best would be to rewrite paragraph to mention variance depending on the platform itself, but even just shameless copy of the existing for Windows adjusted for Mac would help:

# Enable Platform SSO (Mac) in a specific container

Platform SSO is disabled in containers by default ([See bug 1800971](https://bugzilla.mozilla.org/show_bug.cgi?id=1836016)). There's work in progress to add an option in about:preferences#containers. In the meantime, you can enable Platform SSO in a specific container by:

1. Get the container ID. this is available in containers.json in your Firefox profile directory, in a key called userContextId (47001 for example)
2. In about:config, create a boolean key named network.http.microsoft-entra-sso.container-enabled.CONTAINERID, where CONTAINERID is the ID you found in containers.json, and set it to true

**Comment by MrMellie** [comment]
> Can you check this in a recent version? We fixed a problem where we didn't send tokens if one of them was empty.

Still not working for me, though see below
 
> Although it's possible it might be this:
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1934809

That's my bug report as it's now not restricted to the containers.

**Comment by molldk** [comment]
Just to be clear, the issue fixed for me is slightly different from this thread, as I do in fact have sso enabled in my browser.

It sounds like the Device ID aspect is closely tied with sso being enabled, which is what you do not want (platform independent). So I would guess the application code for this is all running only if SSO is turned on in first place.

@mkaply maybe you can help explain..

If I understand correctly, the function "AddWindowsSSO" is used merely to merge the headers, meaning adding the additional required headers including deviceid etc. How is this function called, is it excluded if sso is not enabled? I'm not sure where to look to figure this out.

I found these lines, which to me indicates that the function is called only if SSO is turned on at least:
https://searchfox.org/mozilla-central/source/netwerk/protocol/http/nsHttpChannel.cpp#500-513

I'm not sure how to use mozregression to see if any changes was done here, but looks like the code is from 2021 at least.

**Comment by dannycolin** [comment]
> I would suggest adding the Mac specific settings in the FAQ, but you cannot do PR for the wiki. 

It would be better to document this feature on one of this knowledge pages on support.mozilla.org:

* https://support.mozilla.org/en-US/kb/containers (Multi-Account Containers)
* https://support.mozilla.org/en-US/kb/how-use-firefox-containers (Containers in general)

Anyone can propose modification on this site.

**Comment by smflorentino** [comment]
I submitted a revision request for the KB:
https://support.mozilla.org/en-US/kb/containers/revision/304736

**Comment by creyes-pcty** [comment]
> I would suggest adding the Mac specific settings in the FAQ, but you cannot do PR for the wiki. Tagging [@dannycolin](https://github.com/dannycolin) that seems to make changes in Wiki. Let me know if you want a dedicated issue for this suggestion.
> 
> Best would be to rewrite paragraph to mention variance depending on the platform itself, but even just shameless copy of the existing for Windows adjusted for Mac would help:
> # Enable Platform SSO (Mac) in a specific container
> 
> Platform SSO is disabled in containers by default ([See bug 1800971](https://bugzilla.mozilla.org/show_bug.cgi?id=1836016)). There's work in progress to add an option in about:preferences#containers. In the meantime, you can enable Platform SSO in a specific container by:
> 
>     1. Get the container ID. this is available in containers.json in your Firefox profile directory, in a key called userContextId (47001 for example)
> 
>     2. In about:config, create a boolean key named network.http.microsoft-entra-sso.container-enabled.CONTAINERID, where CONTAINERID is the ID you found in containers.json, and set it to true

Can anyone verify this actually works? I am hesitant to go mucking around with config keys when I have no idea what I'm actually doing here. All my SSO apps that require a device ID do not work under a container but when I am outside a container it works.

**Comment by mkaply** [comment]
> Can anyone verify this actually works? I am hesitant to go mucking around with config keys when I have no idea what I'm actually doing here. All my SSO apps that require a device ID do not work under a container but when I am outside a container it works.

Yes, this is the "documented" way to do this until we build some UI:

https://searchfox.org/firefox-main/source/modules/libpref/init/StaticPrefList.yaml#13859

```
# Whether microsoft-entra-sso is enabled for the default (0) container.
# To enable SSO for additional containers, add a new pref like
# `network.http.microsoft-entra-sso.container-enabled.${containerId}` = true
- name: network.http.microsoft-entra-sso.container-enabled.0
```

**Comment by creyes-pcty** [comment]
> > Can anyone verify this actually works? I am hesitant to go mucking around with config keys when I have no idea what I'm actually doing here. All my SSO apps that require a device ID do not work under a container but when I am outside a container it works.
> 
> Yes, this is the "documented" way to do this until we build some UI:
> 
> https://searchfox.org/firefox-main/source/modules/libpref/init/StaticPrefList.yaml#13859
> 
> ```
> # Whether microsoft-entra-sso is enabled for the default (0) container.
> # To enable SSO for additional containers, add a new pref like
> # `network.http.microsoft-entra-sso.container-enabled.${containerId}` = true
> - name: network.http.microsoft-entra-sso.container-enabled.0
> ```

OK, I tried this and it is still not working on my machine. Something else must be blocking.

**Comment by mariusops** [comment]
> > I would suggest adding the Mac specific settings in the FAQ, but you cannot do PR for the wiki. Tagging [@dannycolin](https://github.com/dannycolin) that seems to make changes in Wiki. Let me know if you want a dedicated issue for this suggestion.
> > Best would be to rewrite paragraph to mention variance depending on the platform itself, but even just shameless copy of the existing for Windows adjusted for Mac would help:
> > # Enable Platform SSO (Mac) in a specific container
> > Platform SSO is disabled in containers by default ([See bug 1800971](https://bugzilla.mozilla.org/show_bug.cgi?id=1836016)). There's work in progress to add an option in about:preferences#containers. In the meantime, you can enable Platform SSO in a specific container by:
> > ```
> > 1. Get the container ID. this is available in containers.json in your Firefox profile directory, in a key called userContextId (47001 for example)
> > 
> > 2. In about:config, create a boolean key named network.http.microsoft-entra-sso.container-enabled.CONTAINERID, where CONTAINERID is the ID you found in containers.json, and set it to true
> > ```
> 
> Can anyone verify this actually works? I am hesitant to go mucking around with config keys when I have no idea what I'm actually doing here. All my SSO apps that require a device ID do not work under a container but when I am outside a container it works.

This worked for me in firefox nightly. Thanks!
