### ISSUE TITLE
Each hidden container is shown twice when choosing to show them

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/multi-account-containers#791]
**[Additional Notes]:**
- On the latest Nightly(57.0a1-20170905220108), the issue is reproducible even when having a single hidden container and choosing to show it.
- The issue is reproducible for any container type (Personal, Work, Banking, Shopping) or any other custom created container type.

**[Affected versions]:**
- Nightly build (57.0a1)
- Firefox Release build (55.0.3)
- Firefox Multi-Account Containers (4.0.1)

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Firefox Multi-Account Containers add-on version (4.0.1 09/06/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on the "Containers" toolbar button.
3. Open two "Personal" tabs and navigate to different websites.
4. Click on the "Containers" toolbar button.
5. Click on the "View Personal container" and choose the "Hide this container" option.
6. Click on the "Containers" toolbar button.
7. Click on the "View Personal container" and choose the "Show this container" option.

**[Expected result]:**	
- Only one instance of each hidden "Personal" container tab is shown.

**[Actual result]:**
- Each hidden "Personal" container tab is shown twice.

**[Notes]**
- Attached a screen recording of the issue:
![containers_duplicated_tabs](https://user-images.githubusercontent.com/20083658/30116710-f2d682f2-9326-11e7-9788-083d10ff0dc5.gif)

**Comment by jonathanKingston** [comment]
This is fixed by #793 with this fix: https://github.com/jonathanKingston/testpilot-containers/commit/3d69c344a9a0303f29b70c3e43820f4cbaa2f271

**Comment by SoftVision-EmilPasca** [comment]
This issue is still reproducible on the latest latest Nightly (57.0a1-20170913220121) with Firefox Multi-Account Containers version (4.0.2 built on 09/14/2017) **when having hidden tabs and choosing the "Move tabs to new window" option from the "Containers" panel.**

This is not reproducible on Windows 10 x64 and Mac OS 10.12 with Firefox Release (53.0.3).

**[Regression]**
Last good revision: 75cd3397298ad5c0f02129a87f465059018a9f63
First bad revision: ec6edd4fec8f62db57c1f075d1d3b536c74af5f8
Pushlog: https://goo.gl/FevcDz

**[Notes]**
- I've also mentioned this in behavior in #797 , @groovecoder, should I log a different issue for this? Should I also log this into bugzilla since this seems more like a Firefox bug?
- Attached a screen recording of the issue:
![reopen_issue](https://user-images.githubusercontent.com/20083658/30431941-d19fbb92-9968-11e7-9008-37e6ec46cc9f.gif)

**Comment by grahamperrin** [comment]
Anecdotally (I don't want to pollute this issue) a few hours ago, during a string of tests with Multi-Account Containers 4.0.3 with Firefox 56.0 (64-bit) on FreeBSD-CURRENT with KDE Plasma 5 beta 5.10.95, I was surprised by some duplication. As far as I recall: 

- it _did_ follow a show (maybe of a container that was hidden before a quit); and 
- the duplication involved multiple windows. 

Unfortunately I can't find any screenshot or recording of the incident, my bad, but I'll keep this issue in mind. 

For what it's worth: [Firefox opening too many windows at start or session restoration time, occasionally opening three copies of a tab in response to a single Control-Click - Firefox Development - Mozilla Discourse](https://discourse.mozilla.org/t/-/19437?u=grahamperrin) … the sprawling screen recording there was of a heavily extended profile. Quite unlike the very clean profiles with which I tested a few hours ago.

**Comment by falolaf** [comment]
I have been experimenting with my own fork of the addon as I wanted to disable the opening of all hidden tabs in a container when I open a new tab in the same container. 
I found out that when this.unhideContainer(tab.cookieStoreId) in the bellow addListener code is commented out the desired behavior is met. I also found out that I do not get any duplicated tabs when doing "Move tabs to new window" with this same change. So it seems this listener thingy is doing something fishy. 

```
browser.tabs.onCreated.addListener((tab) => {
      if (tab.incognito) {
        badge.disableAddon(tab.id);
      }
      // lets remember the last tab created so we can close it if it looks like a redirect
      this.lastCreatedTab = tab;
      if (tab.cookieStoreId) {
        /* This line causes all hidden tabs to be opened if a new tab in a container is created.
           It also seems to duplicate tabs when doing "Move tabs to new window". */
        //this.unhideContainer(tab.cookieStoreId);
      }
      setTimeout(() => {
        this.lastCreatedTab = null;
      }, this.LAST_CREATED_TAB_TIMER);
});
```

**Comment by Progdrasil** [comment]
i'm getting this issue as well, albeit sporadically. It happens when the container "forgets" its saved tabs, then when it remembers them it duplicates them on every re-opening of the container, regardless if i delete them.

* FF 85.0.2
* Multi-account containers 7.2.0
* Manjaro linux (kernel 5.4.97-1)
